const REQUEST = {
  GET: "GET",
  RAW: "Raw",
  GZIP: "gzip",
  NONE: "None",
  TOKEN: "token",
  PARAMS: "Params",
  ACCEPT: "Accept",
  METHOD: "Method",
  REQUEST: "Request",
  DEFLATE: "deflate",
  NO_AUTH: "No Auth",
  ANY_MIME_TYPE: "*/*",
  PASSWORD: "password",
  USERNAME: "username",
  NO_CACHE: "no-cache",
  AUTH: "Authorization",
  FORM_DATA: "Form Data",
  BASIC_AUTH: "Basic Auth",
  CONNECTION: "Connection",
  URL_REQUEST: "Url Request",
  KEEP_ALIVE: "keep-alive",
  CONTENT_TYPE: "Content-Type",
  BEARER_TOKEN: "Bearer Token",
  CACHE_CONTROL: "Cache-Control",
  ACCEPT_ENCODING: "Accept-Encoding",
  FORM_URLENCODED: "x-www-form-urlencoded",
};

export default REQUEST;
